# Generated by Django 3.0.3 on 2020-03-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, help_text='Número do cpf no formato 1111111111', max_length=15, null=True, verbose_name='CPF')),
            ],
        ),
    ]
