# Generated by Django 3.0.3 on 2020-03-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_faculdade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
            ],
        ),
    ]
