# Generated by Django 3.0.3 on 2020-03-13 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_faculdade', '0002_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=128, verbose_name='Sigla')),
                ('data_de_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Inicio')),
                ('realizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_faculdade.Pessoa')),
            ],
        ),
    ]
