# Generated by Django 3.0.3 on 2020-03-13 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_faculdade', '0003_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_faculdade.Pessoa'),
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discricao', models.CharField(max_length=128, verbose_name='Nome')),
                ('valor', models.FloatField()),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_faculdade.Evento')),
            ],
        ),
    ]
