# Generated by Django 3.0.3 on 2020-03-13 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_faculdade', '0004_auto_20200313_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_faculdade.Evento')),
                ('ingresso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_faculdade.Ingresso')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_faculdade.Pessoa')),
            ],
        ),
    ]
